# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'spring-boot-actuator'
    scrape_interval: 5s # Frequency of scraping the Spring Boot application
    metrics_path: '/actuator/prometheus' # Path to the Spring Boot actuator metrics endpoint
    static_configs:
      - targets: ['bank-challenge:8081'] # Spring Boot application endpoint
        labels:
          application: bank-challenge

  - job_name: 'grafana'
    metrics_path: '/'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']